
spring:
   datasource:
     url: jdbc:mysql://115.159.2.127:3306/laiyu?useUnicode=true&characterEncoding=utf-8&useSSL=true
     password:
     username: root
     driver-class-name: com.mysql.jdbc.Driver
   resources:
     static-locations:
server:
  port: 8080






